### ISSUE TITLE
Support https headers (to deploy to gitlab packaging)

### ISSUE THREAD

**Issue by chrisbetz** [clj-commons/pomegranate#111]
Hi,

I want to deploy things into a Gitlab hosted maven repository (see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#authenticating-to-the-gitlab-maven-repository).

For authentication, one needs to pass credentials as an http header, which is usually done via settings.xml in maven.

I'm not sure how to do this in leiningen / pomegranate. Maybe there's a way to add the config to the session (as it is basically passed down as `aether.connector.http.headers` configuration property), maybe there's a better way.

I'm willing to provide a PR for this, but I would first like your advice on how to tackle this in the best way (i.e., least offensive, easiest, ... you name it, way).

Or, maybe I'm just not getting it and pomegranate already supports it and I just missed it.

Any pointers are welcome. Thanks a lot.

Chris

**Comment by chrisbetz** [comment]
Just stumbled over this [gradle-related question](https://stackoverflow.com/questions/53898752/use-gradle-to-upload-archives-to-gitlab-maven-repository) and the [documentation](https://docs.gradle.org/5.0/userguide/repository_types.html#using_http_header_authentication). Maybe the problem's even deeper...

**Comment by cemerick** [comment]
Wow, that approach to authentication is really quite unfortunate. Since Pomegranate has no access to the underlying HTTP abstractions, it's not so simple as adding support for HTTP headers, etc.

I'm not going to work on this, but I think your best bet will be to follow the pattern set by https://github.com/s3-wagon-private/s3-wagon-private, probably subclassing whatever the usual HTTPS wagon is. That will allow you to access the username/passphrase info set in the usual way via Leiningen (and thus obviates the need for any changes there), set the custom Gitlab headers as necessary, and otherwise let everything else work as it usually does.

**Comment by chrisbetz** [comment]
Hi Chas,

thanks for taking the time to look into this. Actually, I'm really annoyed
by that authentication mechanism, and it might well be one (of a number of)
reason(s) to not use Gitlab Maven repos. However, while looking into this,
I found out that other tools are also using this, and also that other tools
share the problem (Clojure deps, Scala's SBT, among others). Also, aether
is a mess to deal with.

So, thanks for your thoughts. For me, you might close this issue, the
effort necessary is not worth it, especially if you also think it's not
easy to address from within pomegranate. Your hint on s3-wagon-private
would be the way to go for me then should I come back to this.

Cheers,

Chris

**Comment by craigmalone** [comment]
Just for completeness, I had a similar need to access GitLab maven repositories from leiningen.

I followed the solution outlined above to create a small HttpWagon wrapper and works fine for accessing our GitLab private repos from lein.

If anyone needs this, it is available at:

https://github.com/nicheware/lein-gitlab-wagon
